version: '3.8'

services:
  mysql:
    container_name: 'insider_case_mysql'
    build:
      context: './docker/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-secret}'
      MYSQL_USER: '${MYSQL_USER:-admin}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-admin}'
    ports:
      - '3396:3306'
  php:
    container_name: 'insider_case_php'
    build:
      context: './docker/php-fpm'
    volumes:
      - './:/var/www/site'
    depends_on:
      - mysql
  nginx:
    container_name: 'insider_case_nginx'
    build:
      context: './docker/nginx'
    ports:
      - '8091:80'
    volumes:
      - './:/var/www/site'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
